---
name: "Refresh dev dependencies"
"on":
  schedule:
    # Weekly
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      reset-branch:
        type: boolean
        default: false
      labels:
        required: false
        type: string

jobs:
  refresh:
    strategy:
      fail-fast: false
      matrix:
        include:
          - base-branch: devel
            pr-branch: pip-compile/devel/dev
            nox-args: >-
              -e 'pip-compile(formatters)'
              'pip-compile(typing)'
              'pip-compile(static)'
              'pip-compile(spelling)'
              'pip-compile(tag)'
            python-versions: "3.11"
          - base-branch: stable-2.18
            pr-branch: pip-compile/stable-2.18/dev
            nox-args: >-
              -e 'pip-compile(formatters)'
              'pip-compile(typing)'
              'pip-compile(static)'
              'pip-compile(spelling)'
            python-versions: "3.11"
          - base-branch: stable-2.17
            pr-branch: pip-compile/stable-2.17/dev
            nox-args: >-
              -e 'pip-compile(formatters)'
              'pip-compile(typing)'
              'pip-compile(static)'
              'pip-compile(spelling)'
            python-versions: "3.10"
          - base-branch: stable-2.16
            pr-branch: pip-compile/stable-2.16/dev
            nox-args: >-
              -e 'pip-compile(formatters)'
              'pip-compile(typing)'
              'pip-compile(static)'
              'pip-compile(spelling)'
            python-versions: "3.10"
    name: "Refresh dev dependencies"
    uses: ./.github/workflows/reusable-pip-compile.yml
    with:
      message: "ci: refresh dev dependencies"
      base-branch: "${{ matrix.base-branch }}"
      pr-branch: "${{ matrix.pr-branch }}"
      nox-args: "${{ matrix.nox-args }}"
      python-versions: "${{ matrix.python-versions }}"
      reset-branch: "${{ inputs.reset-branch || false }}"
      labels: "${{ inputs.labels || 'no_backport,tooling' }}"
    secrets: inherit
