# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_postgres_chaos_testing_02_mem_hog_chaos_experiment]
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Give a memory hog on a node belonging to a deployment
kind: ChaosExperiment
metadata:
  name: node-memory-hog
  labels:
    name: node-memory-hog
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: ci
spec:
  definition:
    scope: Cluster
    permissions:
      # Create and monitor the experiment & helper pods
      - apiGroups: [""]
        resources: ["pods"]
        verbs:
          [
            "create",
            "delete",
            "get",
            "list",
            "patch",
            "update",
            "deletecollection",
          ]
      # Performs CRUD operations on the events inside chaosengine and chaosresult
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create", "get", "list", "patch", "update"]
      # Fetch configmaps details and mount it to the experiment pod (if specified)
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get", "list"]
      # Track and get the runner, experiment, and helper pods log
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get", "list", "watch"]
      # for creating and managing to execute commands inside target container
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["get", "list", "create"]
      # for configuring and monitor the experiment job by the chaos-runner pod
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create", "list", "get", "delete", "deletecollection"]
      # for creation, status polling and deletion of litmus chaos resources used within a chaos workflow
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines", "chaosexperiments", "chaosresults"]
        verbs: ["create", "list", "get", "patch", "update", "delete"]
      # for experiment to perform node status checks
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list"]
    image: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:latest"
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name node-memory-hog
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "120"

      ## Specify the size as percent of total node capacity Ex: '30'
      ## NOTE: for selecting this option keep MEMORY_CONSUMPTION_MEBIBYTES empty
      - name: MEMORY_CONSUMPTION_PERCENTAGE
        value: ""

      ## Specify the amount of memory to be consumed in mebibytes
      ## NOTE: for selecting this option keep MEMORY_CONSUMPTION_PERCENTAGE empty
      - name: MEMORY_CONSUMPTION_MEBIBYTES
        value: ""

      - name: NUMBER_OF_WORKERS
        value: "1"

      # ENTER THE COMMA SEPARATED TARGET NODES NAME
      - name: TARGET_NODES
        value: ""

      - name: NODE_LABEL
        value: ""

      # Period to wait before and after injection of chaos in sec
      - name: RAMP_TIME
        value: ""

      # provide lib image
      - name: LIB_IMAGE
        value: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:latest"

      - name: DEFAULT_HEALTH_CHECK
        value: "false"

      ## percentage of total nodes to target
      - name: NODES_AFFECTED_PERC
        value: ""

      ## it defines the sequence of chaos execution for multiple target nodes
      ## supported values: serial, parallel
      - name: SEQUENCE
        value: "parallel"

    labels:
      name: node-memory-hog
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: ci
# [END gke_databases_postgres_chaos_testing_02_mem_hog_chaos_experiment]