services:
  linkedinfrontend:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "3000:3000"  
      - "80:80"
    depends_on:
      - db
    networks:
      - linkedinnet
  nodebackend: 
    build:
      context: ./server
      dockerfile: Dockerfile.be
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
    networks:
      - linkedinnet
  db:
    volumes:
      - linkedin_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - linkedinnet  

volumes:
   linkedin_db:

networks:
  linkedinnet:
