apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  rules:
  - host: "web.exemple.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mon-service-web
            port:
              number: 80
