# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# @TODO: replace all placeholders
# @TODO: file name should be <category>-<sample-title>-ci.yml
# @TODO: see examples in the workflows/ directory for inspiration.)

name: <FILE_NAME>
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/<FILE_NAME>.yml'
      - '<PATH/TO/SAMPLE>/**'
  pull_request:
    paths:
      - '.github/workflows/<FILE_NAME>.yml'
      - '<PATH/TO/SAMPLE>/**'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # @TODO: Use a step like this to build container images
      - name: Build container image
        run: |
          cd <PATH/TO/DOCKERFILE>
          docker build --tag <CONTAINER_NAME> .
      # @TODO: Use a step like this to validate Terraform scripts
      - name: Validate Terraform config
        run: |
          cd <PATH/TO/TF>
          terraform init
          terraform validate
