name: ai-ml-a100-jax-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ai-ml-gke-a100-jax-ci.yml'
      - 'ai-ml/gke-a100-jax/**'
  pull_request:
    paths:
      - '.github/workflows/ai-ml-gke-a100-jax-ci.yml'
      - 'ai-ml/gke-a100-jax/**'
jobs:
  gke-a100-jax:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build tensorflow container for gke-a100-jax tutorial
        run: |
          cd ai-ml/gke-a100-jax
          docker build --tag tensorflow .
