version: '3.3'

services:
  
  web:
    image: dockersamples/aspnet-monitoring-website:4.7.2
    ports:
    - "80"
    networks:
      - app-net    

  prometheus:
    image: dockersamples/aspnet-monitoring-prometheus:2.3.1
    ports:
    - "9090"
    networks:
      - app-net 

networks:
  app-net:
    external:
      name: nat